import { NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { generateRecipe } from "@/lib/ai";
import { saveCocktail } from "@/lib/store";
import type { Cocktail } from "@/lib/types";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

// Step 1 of 2: return the recipe immediately. The image is generated by a
// separate /api/generate-image call so neither request hits the function timeout.
export async function POST(req: Request) {
  try {
    const { prompt, mocktail } = await req.json();
    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return NextResponse.json({ error: "Please enter something." }, { status: 400 });
    }
    const cleanPrompt = prompt.trim().slice(0, 500);
    const isMocktail = Boolean(mocktail);

    const recipe = await generateRecipe(cleanPrompt, { mocktail: isMocktail });
    const id = randomUUID();

    const cocktail: Cocktail = {
      id,
      prompt: cleanPrompt,
      name: recipe.name,
      tagline: recipe.tagline,
      description: recipe.description,
      glassware: recipe.glassware,
      garnish: recipe.garnish,
      prepTime: recipe.prepTime,
      difficulty: recipe.difficulty,
      mocktail: isMocktail,
      ingredients: recipe.ingredients,
      instructions: recipe.instructions,
      imageUrl: "",
      createdAt: new Date().toISOString(),
    };

    await saveCocktail(cocktail);
    // Return the saved recipe plus the imagePrompt the client needs for step 2.
    return NextResponse.json({ ...cocktail, imagePrompt: recipe.imagePrompt });
  } catch (err: any) {
    console.error("Generation error:", err);
    return NextResponse.json(
      { error: err?.message || "Something went wrong generating your cocktail." },
      { status: 500 }
    );
  }
}
